name: Build WinForms (.NET 8) Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # WinForms 需要 Windows 环境编译

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MyWinFormsApp.sln

    - name: Build in Release mode
      run: dotnet build MyWinFormsApp.sln -c Release

    - name: Publish self-contained (可选)
      run: dotnet publish MyWinFormsApp/MyWinFormsApp.csproj -c Release -o Build/ReleasePublish --self-contained false

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ReleaseBuild
        path: Build/Release
